#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES from the module graph.
#
# BSD and ISC dependencies require their copyright notice to travel with a
# binary distribution, so the notices are generated from the actual license
# texts rather than kept by hand. Run this whenever dependencies change; CI
# checks that the committed file is up to date.
#
# Needs github.com/google/go-licenses on PATH or GOBIN:
#   go install github.com/google/go-licenses@latest
set -euo pipefail

cd "$(dirname "$0")/.."

out="THIRD_PARTY_NOTICES"
pkg="./cmd/localport"

gl="$(command -v go-licenses || true)"
if [ -z "$gl" ]; then
	for c in "$(go env GOBIN)" "${GOPATH:-$HOME/go}/bin" "$HOME/go/bin"; do
		if [ -x "$c/go-licenses" ]; then gl="$c/go-licenses"; break; fi
	done
fi
if [ -z "$gl" ]; then
	echo "go-licenses not found. Install it with:" >&2
	echo "  go install github.com/google/go-licenses@latest" >&2
	exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# The report gives module -> license type; the saved tree gives the verbatim
# text. The agent itself is dropped (its own LICENSE ships separately).
"$gl" save "$pkg" --save_path="$tmp/save" --force 2>/dev/null
report="$("$gl" report "$pkg" 2>/dev/null | grep -v '^github.com/localport/agent,')"

{
	echo "Localport CLI Agent - Third-Party Notices"
	echo
	echo "The Localport CLI Agent (Apache License, Version 2.0) is built with the"
	echo "open-source components below. Each is distributed under its own license,"
	echo "reproduced verbatim. Generated by scripts/gen-third-party-notices.sh from"
	echo "the module graph; do not edit by hand."
	echo
	while IFS=, read -r module _url license; do
		[ -z "$module" ] && continue
		# The license file sits at the module root in the saved tree; a package
		# path (x/crypto/pbkdf2) resolves up to wherever the LICENSE lives.
		lic=""
		path="$module"
		while [ -n "$path" ] && [ "$path" != "." ]; do
			f="$(find "$tmp/save/$path" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'COPYING*' \) 2>/dev/null | head -1 || true)"
			if [ -n "$f" ]; then lic="$f"; break; fi
			path="$(dirname "$path")"
		done
		echo "=============================================================================="
		echo "$module"
		echo "$license"
		echo "=============================================================================="
		echo
		if [ -n "$lic" ]; then cat "$lic"; else echo "(license text unavailable)"; fi
		echo
	done <<< "$report"
} > "$out"

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
